### ISSUE TITLE
Let's Make Contributors Pages

### ISSUE THREAD

**Issue by hsk** [maekawatoshiki/lit-x86#10]
Hi all.
I hope contributors page like ruby.
http://docs.ruby-lang.org/en/2.3.0/contributors_rdoc.html

Let's making of contributors page.

thank's h_sakurai.

**Comment by maekawatoshiki** [comment]
Yeah, I'll think about that:)

**Comment by hsk** [comment]
Thank you.

前向きにお願いします。
Please examine that positively.
