### ISSUE TITLE
Writing Specification of Lit language

### ISSUE THREAD

**Issue by hsk** [maekawatoshiki/lit-x86#11]
I interesting programming language specification, now.
Let's writing specification of Lit language.
I found specification of lit on wiki. nice.
I think that if various discussion here.
What do you think?

プログラミング言語の仕様に興味がある今日この頃です。
Lit言語の仕様を書きましょう!
wikiにしよう書いてあるのを見つけました。素晴らしいです。
ここで色々議論できればと思います。いいでしょうか？

**Comment by maekawatoshiki** [comment]
Hi. Sorry to be late..
I'm  writing reference now. But

**Comment by maekawatoshiki** [comment]
OK. I wanna diccussion, too!

**Comment by hsk** [comment]
Thank you.
OK, first question.
それでは質問です。

Program inner syntax element is eval sequence spilit \n.
Why eval element name is eval?

まず、プログラムの中身の構文要素は、evalの連続で、改行が間に複数入ったものですが、なぜ、評価という名前にしたのか教えてください。

program      ::= eval
eval         ::= ";"\* (expression (";"_))_

expression_listとかexpr_list, expressions, exprsとかのほうが良いような気がするのですが。

**Comment by hsk** [comment]
適当な英語＆日本語ですいませんｗ

**Comment by maekawatoshiki** [comment]
- It's not a meaning especially. I just like the word 'eval' LOL

**Comment by maekawatoshiki** [comment]
私も、今から日本語で話しますね
