### ISSUE TITLE
No explicit copyright notice found

### ISSUE THREAD

**Issue by jserv** [maekawatoshiki/lit-x86#3]
There is no explicit copyright information found in whole source tree. Can you clarify?

**Comment by maekawatoshiki** [comment]
Oh!
Since had personally developed, I forgot.
I'll write copyright in README.md.
Thank you :)

**Comment by jserv** [comment]
I saw the recent changes which mention the proper copyright holder. Can you please consider to relicense the project in [open source compliant terms](http://opensource.org/osd-annotated)?

**Comment by maekawatoshiki** [comment]
OK. I will adapt the BSD License to this project.

**Comment by jserv** [comment]
@maekawatoshiki: Thanks again for your generous work!
