### ISSUE TITLE
File '.DS_Store' should be removed

### ISSUE THREAD

**Issue by jserv** [maekawatoshiki/lit-x86#4]
The file `.DS_Store` should not be tracked by Git repository. Instead, [gitignore](http://git-scm.com/docs/gitignore) can help developers to exclude the unwanted files.

**Comment by maekawatoshiki** [comment]
OK. I'll learn about gitignore.

**Comment by maekawatoshiki** [comment]
I added .gitignore and removed .DS_Store:)
