### ISSUE TITLE
Program "examples/miller.rb" fails to execute

### ISSUE THREAD

**Issue by jserv** [maekawatoshiki/lit-x86#5]
Test environment: Ubuntu Linux 14.04 x86_64

How to reproduce:

```
./lit examples/miller.rb
```

The last messages:

```
string addr> 147964944
...
memsz: 2
size: 911byte, 1.39%
Segmentation fault (core dumped)
```

**Comment by maekawatoshiki** [comment]
I see. realloc() usage was incorrect. I fixed that bug:)

**Comment by jserv** [comment]
Verified OK with commit d7b7c04f43c612f9b22be6a49bde385bacee12a0 .

Thanks!
